### ISSUE TITLE
Create new screen shots for the chrome store

### ISSUE THREAD

**Issue by MariuszDabrowski** [notisnan/covid19-tracker#12]
A couple of different screen shots that users can scroll through to give them an idea of what the app experience is like.

**Comment by MariuszDabrowski** [comment]
![640x400](https://user-images.githubusercontent.com/4285139/77863867-89bbcf80-71f3-11ea-9fbe-cbd5b60cc553.jpg)

This is for the screenshot on the google chrome store.

@duliodenis just close once updated.

**Comment by duliodenis** [comment]
Looks amazing - thank you. Updated!
