### ISSUE TITLE
Stats Rounding Issue

### ISSUE THREAD

**Issue by duliodenis** [notisnan/covid19-tracker#4]
Statistics like 81,394 round to 81.3 instead of 81.4K.
![Screen Shot 2020-03-28 at 5 50 11 PM](https://user-images.githubusercontent.com/1795788/77834672-b7821500-711c-11ea-9c01-e5ae037c86f9.png)

**Comment by MariuszDabrowski** [comment]
Complete in pull request, merge, test, and push when ready!
