### ISSUE TITLE
Need to handle N/A values in country data

### ISSUE THREAD

**Issue by sdangit** [notisnan/covid19-tracker#69]
Currently, the API is returning { total_recovered: "N/A"} for the UK.  This results in the UI showing ".m" in the Recovered column for that country.  Presumably, this could happen for any of the data.

Perhaps this should display nothing (e.g. blank / empty string) rather than the confusing ".m"?

**Comment by MariuszDabrowski** [comment]
Thanks for bringing this up Steve, we noticed this a few days ago and have been keeping an eye on the issue report to the API provider here: https://rapidapi.com/astsiatsko/api/coronavirus-monitor/discussions/15069/Cases-by-country

Great point on dealing with a non expected value. 

I was thinking leaving it blank might cause the user to questions whether the data is broken, it's similar to failing silently. Putting `N/A` would give the user some sort of feedback as to why that data is not available.

What are your thoughts?

**Comment by sdangit** [comment]
I used an empty string for personally aesthetic reasons, but you're right, N/A would be more technically accurate and communicate better to the user that the data is not available.
